baseURL = "/"
title = "Gain N Go"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
buildFuture = true
buildExpired = true
disqusShortname = "gainngo"

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Blog by Gain N go"
author = "TheLoneRanger"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true
images = [ "https://images.unsplash.com/photo-1437773540554-96d393b4d0c9?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1356&q=80" ]

  [params.assets]
  favicon = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"
  favicon16x16 = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"
  favicon32x32 = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"
  apple_touch_icon = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"
  safari_pinned_tab = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"

  [params.label]
  text = "Home"
  icon = "https://i.ibb.co/N31zCvQ/ms-icon-310x310.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Gain N Go"
  imageUrl = "https://i.ibb.co/fkGj6rG/96a5cf08-3e5b-47e5-85b9-5dadbaed1a5a-200x200.png" 
  imageTitle = "logo"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

    [[params.profileMode.buttons]]
    name = "All Posts"
    url = "posts"

  [params.homeInfoParams]
  Title = "Welcome to Gain N Go"
  Content = """
Welcome to demo of hugo's theme PaperMod.
- **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
- Do give a 🌟 on Github !
- PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://facebook.com/"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
